server:
  port: 8088
  
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HyunSeungBum/SpringCloudExam.git
          search-paths: Application-Config
          default-label: master
          force-pull: true
